# Generated by Django 4.2.6 on 2024-01-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnookerMatch',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('player1_id', models.IntegerField()),
                ('player2_id', models.IntegerField()),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('player1_walkover', models.BooleanField()),
                ('player2_walkover', models.BooleanField()),
                ('best_of', models.IntegerField()),
                ('winner_id', models.IntegerField()),
                ('match_datetime', models.DateTimeField()),
            ],
        ),
    ]
