# Generated by Django 4.2.6 on 2024-01-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snooker_ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snookermatch',
            name='match_season',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
